### ISSUE TITLE
Cannot rebuild using electron rebuild

### ISSUE THREAD

**Issue by muminasaad** [jfromaniello/node-windows-eventlog#14]
Adding the module to Electron application then rebuilding it will show the following error then fail.

An unhandled error occurred inside electron-rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  EventLog.cpp
  win_delay_load_hook.cc
..\src\EventLog.cpp(110): warning C4996: 'v8::Function::NewInstance': was declared deprecated [c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbac
kClientHost\node_modules\windows-eventlog\build\EventLog.vcxproj]
  C:\Users\Mumin.SEDCO-ONLINE\.electron-gyp\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(3644): note: see declaration of 'v8::Function::NewInstance'
LINK : fatal error LNK1104: cannot open file 'node.lib' [c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\windows-event
log\build\EventLog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\node-gyp\lib\build.js:258:2
3)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "c:\\TFSProjects\\CVM\\Main\\Branch\\CustomerFeedbackClient\\CustomerFeedbackClientHost\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.11" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\windows-eventlog
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  EventLog.cpp
  win_delay_load_hook.cc
..\src\EventLog.cpp(110): warning C4996: 'v8::Function::NewInstance': was declared deprecated [c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbac
kClientHost\node_modules\windows-eventlog\build\EventLog.vcxproj]
  C:\Users\Mumin.SEDCO-ONLINE\.electron-gyp\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(3644): note: see declaration of 'v8::Function::NewInstance'
LINK : fatal error LNK1104: cannot open file 'node.lib' [c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\windows-event
log\build\EventLog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\node-gyp\lib\build.js:258:2
3)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "c:\\TFSProjects\\CVM\\Main\\Branch\\CustomerFeedbackClient\\CustomerFeedbackClientHost\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.11" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\windows-eventlog
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\spawn-rx\lib\src\index.js:241:65)
    at SafeSubscriber.__tryOrUnsub (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (c:\TFSProjects\CVM\Main\Branch\CustomerFeedbackClient\CustomerFeedbackClientHost\node_modules\rxjs\Subscriber.js:185:22)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Mumin.SEDCO-ONLINE\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"

npm ERR! node v6.11.2
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! customer-feedback-client@1.0.0 rebuild: `electron-rebuild -f`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the customer-feedback-client@1.0.0 rebuild script 'electron-rebuild -f'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the customer-feedback-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs customer-feedback-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls customer-feedback-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mumin.SEDCO-ONLINE\AppData\Roaming\npm-cache\_logs\2017-08-27T15_13_04_008Z-debug.log

**Comment by 0x7f** [comment]
Hi @muminasaad thanks for the report. Can you point me to a repo/project which I can use to reproduce the issue? Also just upgraded the dependencies and fixed the NewFunction deprecation warning. Maybe this helps already.

**Comment by muminasaad** [comment]
Sorry @0x7f , i dont have a repo , but if you create the simplest electron application and try to rebuild the project you will notice that it will fail directly,

**Comment by cevn** [comment]
I'm having this problem as well.
